# Generated by Django 5.1.2 on 2024-10-14 18:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe_eat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='complaints',
            new_name='complaint',
        ),
        migrations.RenameModel(
            old_name='restaurants',
            new_name='restaurant',
        ),
    ]
