# Generated by Django 5.1.2 on 2024-10-14 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe_eat', '0003_restaurant_cuisine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='cuisine',
        ),
    ]
