# Generated by Django 5.1.2 on 2024-10-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_eat', '0005_restaurant_cuisine'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='trade_license_no',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
