# Generated by Django 5.1.2 on 2024-10-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_eat', '0006_restaurant_trade_license_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
