# Generated by Django 5.1.2 on 2024-10-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_eat', '0007_alter_restaurant_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='trade_license_no',
            new_name='trade_License_Number',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='no_of_Employee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
