# Generated by Django 5.1.2 on 2024-10-14 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe_eat', '0011_restaurant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='image',
        ),
    ]
