# Generated by Django 5.0.3 on 2024-11-08 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_eat', '0014_complaint_complaint_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_pic',
            field=models.ImageField(blank=True, null=True, upload_to='complaints/'),
        ),
        migrations.CreateModel(
            name='ComplaintPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='complaints/')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='safe_eat.complaint')),
            ],
        ),
    ]
