# Generated by Django 5.0.3 on 2024-11-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_eat', '0015_complaint_complaint_pic_complaintpic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaintpic',
            old_name='complaint',
            new_name='complaint_instance',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='complaint_pic',
        ),
        migrations.AlterField(
            model_name='complaintpic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='complaint_pic',
            field=models.ManyToManyField(blank=True, null=True, related_name='complaints', to='safe_eat.complaintpic'),
        ),
    ]
