# Generated by Django 5.0.3 on 2024-11-08 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe_eat', '0016_rename_complaint_complaintpic_complaint_instance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='complaint_pic',
        ),
        migrations.DeleteModel(
            name='ComplaintPic',
        ),
    ]
