# Generated by Django 5.0.2 on 2024-11-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_eat', '0017_remove_complaint_complaint_pic_delete_complaintpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
