# Generated by Django 5.0.2 on 2024-11-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_eat', '0021_alter_complaint_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('trade_License_Number', models.CharField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('cuisine', models.CharField(blank=True, max_length=500, null=True)),
                ('no_of_Employee', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pending_restaurants/')),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
