# Generated by Django 5.0.2 on 2024-11-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_eat', '0024_alter_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, default='static/images/static/images/no_logo.jpg', null=True, upload_to=''),
        ),
    ]
